### GET POST BY ID
GET http://localhost:8085/v1/posts/1
Content-Type: application/json

###

### CREATE A POST
POST http://localhost:8085/v1/posts/
Content-Type: application/json

{
  "title": "My Stori",
  "content": "Dimulai dari...",
  "tags": [
    "Romance"
  ]
}

