### GET POST BY ID
GET http://localhost:8085/v1/users/3
Content-Type: application/json

### CREATE A POST
POST http://localhost:8085/v1/users/
Content-Type: application/json

{
  "name": "Edwin",
  "email": "edwinrhema@gmail.com",
  "password": "admin123"
}

### FOLLOW A USER
PUT http://localhost:8085/v1/users/1/follow
Content-Type: application/json

{
  "user_id": 2
}

### UNFOLLOW A USER
PUT http://localhost:8085/v1/users/1/unfollow
Content-Type: application/json

{
  "user_id": 2
}